twig:
  file_name_pattern: '*.twig'
  globals:
    app_locale: '%app_locale%'
    app_albumService: '@App\Service\Hub\AlbumService'
    app_moodService: '@App\Service\Hub\MoodService'
    app_suggestService: '@App\Service\Match\SuggestService'

when@test:
  twig:
    strict_variables: true
