<?php

namespace App\DataFixtures\Hub;

use App\Entity\Hub\Album;
use App\Entity\Hub\Artist;
use App\Entity\Hub\Genre;
use App\Entity\Hub\Mood;
use App\Entity\Hub\Style;
use App\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class AlbumFixtures extends Fixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager): void
    {
        $datas = [
            [
                'title' => 'Abbey Road',
                'cover' => '1-placeholder.png',
                'year' => '1969',
                'artist' => 'the-beatles',
                'genre' => 'rock',
                'style' => 'classique',
                'owner' => 'nicolas',
                'moods' => ['paisible', 'amoureux'],
                'reference' => 'abbey-road',
            ],
            [
                'title' => 'The Wall',
                'cover' => '1-placeholder.png',
                'year' => '1979',
                'artist' => 'pink-floyd',
                'genre' => 'rock',
                'style' => 'progressif',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'concentre'],
                'reference' => 'the-wall',
            ],
            [
                'title' => 'Led Zeppelin IV',
                'cover' => '1-placeholder.png',
                'year' => '1971',
                'artist' => 'led-zeppelin',
                'genre' => 'rock',
                'style' => 'hard',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'led-zeppelin-iv',
            ],
            [
                'title' => 'Nevermind',
                'cover' => '1-placeholder.png',
                'year' => '1991',
                'artist' => 'nirvana',
                'genre' => 'grunge',
                'owner' => 'nicolas',
                'moods' => ['motive', 'melancolique'],
                'reference' => 'nevermind',
            ],
            [
                'title' => 'Master of Puppets',
                'cover' => '1-placeholder.png',
                'year' => '1986',
                'artist' => 'metallica',
                'genre' => 'metal',
                'style' => 'thrash',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'master-of-puppets',
            ],
            [
                'title' => 'A Night at the Opera',
                'cover' => '1-placeholder.png',
                'year' => '1975',
                'artist' => 'queen',
                'genre' => 'rock',
                'style' => 'progressif',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'a-night-at-the-opera',
            ],
            [
                'title' => 'Paranoid',
                'cover' => '1-placeholder.png',
                'year' => '1970',
                'artist' => 'black-sabbath',
                'genre' => 'metal',
                'style' => 'heavy',
                'owner' => 'nicolas',
                'moods' => ['motive', 'melancolique'],
                'reference' => 'paranoid',
            ],
            [
                'title' => 'The Dark Side of the Moon',
                'cover' => '1-placeholder.png',
                'year' => '1973',
                'artist' => 'pink-floyd',
                'genre' => 'rock',
                'style' => 'progressif',
                'owner' => 'nicolas',
                'moods' => ['paisible', 'concentre'],
                'reference' => 'the-dark-side-of-the-moon',
            ],
            [
                'title' => 'American IV: The Man Comes Around',
                'cover' => '1-placeholder.png',
                'year' => '2002',
                'artist' => 'johnny-cash',
                'genre' => 'country',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'paisible'],
                'reference' => 'american-iv-the-man-comes-around',
            ],
            [
                'title' => 'Mezzanine',
                'cover' => '1-placeholder.png',
                'year' => '1998',
                'artist' => 'massive-attack',
                'genre' => 'electro',
                'style' => 'trip-hop',
                'owner' => 'nicolas',
                'moods' => ['concentre', 'melancolique'],
                'reference' => 'mezzanine',
            ],
            [
                'title' => 'Homework',
                'cover' => '1-placeholder.png',
                'year' => '1997',
                'artist' => 'daft-punk',
                'genre' => 'electro',
                'style' => 'house',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'homework',
            ],
            [
                'title' => 'Meteora',
                'cover' => '1-placeholder.png',
                'year' => '2003',
                'artist' => 'linkin-park',
                'genre' => 'rock',
                'style' => 'nu-metal',
                'owner' => 'nicolas',
                'moods' => ['motive', 'melancolique'],
                'reference' => 'meteora',
            ],
            [
                'title' => 'Blonde',
                'cover' => '1-placeholder.png',
                'year' => '2016',
                'artist' => 'frank-ocean',
                'genre' => 'rnb',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'paisible'],
                'reference' => 'blonde',
            ],
            [
                'title' => 'Toxicity',
                'cover' => '1-placeholder.png',
                'year' => '2001',
                'artist' => 'system-of-a-down',
                'genre' => 'metal',
                'style' => 'nu-metal',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'toxicity',
            ],
            [
                'title' => 'Discovery',
                'cover' => '1-placeholder.png',
                'year' => '2001',
                'artist' => 'daft-punk',
                'genre' => 'electro',
                'style' => 'house',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'discovery',
            ],
            [
                'title' => 'Grace',
                'cover' => '1-placeholder.png',
                'year' => '1994',
                'artist' => 'jeff-buckley',
                'genre' => 'rock',
                'style' => 'alternatif',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'amoureux'],
                'reference' => 'grace',
            ],
            [
                'title' => 'Kid A',
                'cover' => '1-placeholder.png',
                'year' => '2000',
                'artist' => 'radiohead',
                'genre' => 'rock',
                'style' => 'experimental',
                'owner' => 'nicolas',
                'moods' => ['concentre', 'melancolique'],
                'reference' => 'kid-a',
            ],
            [
                'title' => 'Is This It',
                'cover' => '1-placeholder.png',
                'year' => '2001',
                'artist' => 'the-strokes',
                'genre' => 'rock',
                'style' => 'garage',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'is-this-it',
            ],
            [
                'title' => 'Violator',
                'cover' => '1-placeholder.png',
                'year' => '1990',
                'artist' => 'depeche-mode',
                'genre' => 'electro',
                'style' => 'synth-pop',
                'owner' => 'nicolas',
                'moods' => ['concentre', 'melancolique'],
                'reference' => 'violator',
            ],
            [
                'title' => 'The Bends',
                'cover' => '1-placeholder.png',
                'year' => '1995',
                'artist' => 'radiohead',
                'genre' => 'rock',
                'style' => 'alternatif',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'concentre'],
                'reference' => 'the-bends',
            ],
            [
                'title' => 'Lateralus',
                'cover' => '1-placeholder.png',
                'year' => '2001',
                'artist' => 'tool',
                'genre' => 'metal',
                'style' => 'progressif',
                'owner' => 'nicolas',
                'moods' => ['concentre', 'melancolique'],
                'reference' => 'lateralus',
            ],
            [
                'title' => 'Rumours',
                'cover' => '1-placeholder.png',
                'year' => '1977',
                'artist' => 'fleetwood-mac',
                'genre' => 'rock',
                'style' => 'soft',
                'owner' => 'nicolas',
                'moods' => ['amoureux', 'melancolique'],
                'reference' => 'rumours',
            ],
            [
                'title' => 'Currents',
                'cover' => '1-placeholder.png',
                'year' => '2015',
                'artist' => 'tame-impala',
                'genre' => 'rock',
                'style' => 'psychedelique',
                'owner' => 'nicolas',
                'moods' => ['paisible', 'concentre'],
                'reference' => 'currents',
            ],
            [
                'title' => 'Hot Fuss',
                'cover' => '1-placeholder.png',
                'year' => '2004',
                'artist' => 'the-killers',
                'genre' => 'rock',
                'style' => 'indie',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'hot-fuss',
            ],
            [
                'title' => 'The Queen Is Dead',
                'cover' => '1-placeholder.png',
                'year' => '1986',
                'artist' => 'the-smiths',
                'genre' => 'rock',
                'style' => 'indie',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'paisible'],
                'reference' => 'the-queen-is-dead',
            ],
            [
                'title' => 'Random Access Memories',
                'cover' => '1-placeholder.png',
                'year' => '2013',
                'artist' => 'daft-punk',
                'genre' => 'electro',
                'style' => 'disco',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'random-access-memories',
            ],
            [
                'title' => 'Merriweather Post Pavilion',
                'cover' => '1-placeholder.png',
                'year' => '2009',
                'artist' => 'animal-collective',
                'genre' => 'electro',
                'style' => 'experimental',
                'owner' => 'nicolas',
                'moods' => ['paisible', 'concentre'],
                'reference' => 'merriweather-post-pavilion',
            ],
            [
                'title' => 'Channel Orange',
                'cover' => '1-placeholder.png',
                'year' => '2012',
                'artist' => 'frank-ocean',
                'genre' => 'rnb',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'amoureux'],
                'reference' => 'channel-orange',
            ],
            [
                'title' => 'Yankee Hotel Foxtrot',
                'cover' => '1-placeholder.png',
                'year' => '2002',
                'artist' => 'wilco',
                'genre' => 'rock',
                'style' => 'alternatif',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'concentre'],
                'reference' => 'yankee-hotel-foxtrot',
            ],
            [
                'title' => 'AM',
                'cover' => '1-placeholder.png',
                'year' => '2013',
                'artist' => 'arctic-monkeys',
                'genre' => 'rock',
                'style' => 'indie',
                'owner' => 'nicolas',
                'moods' => ['en-soiree', 'motive'],
                'reference' => 'am',
            ],
            [
                'title' => 'Blackstar',
                'cover' => '1-placeholder.png',
                'year' => '2016',
                'artist' => 'david-bowie',
                'genre' => 'rock',
                'style' => 'experimental',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'concentre'],
                'reference' => 'blackstar',
            ],
            [
                'title' => 'Dummy',
                'cover' => '1-placeholder.png',
                'year' => '1994',
                'artist' => 'portishead',
                'genre' => 'electro',
                'style' => 'trip-hop',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'concentre'],
                'reference' => 'dummy',
            ],
            [
                'title' => 'Automatic for the People',
                'cover' => '1-placeholder.png',
                'year' => '1992',
                'artist' => 'r-e-m',
                'genre' => 'rock',
                'style' => 'alternatif',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'paisible'],
                'reference' => 'automatic-for-the-people',
            ],
            [
                'title' => 'Songs for the Deaf',
                'cover' => '1-placeholder.png',
                'year' => '2002',
                'artist' => 'queens-of-the-stone-age',
                'genre' => 'rock',
                'style' => 'stoner',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'songs-for-the-deaf',
            ],
            [
                'title' => 'Doolittle',
                'cover' => '1-placeholder.png',
                'year' => '1989',
                'artist' => 'pixies',
                'genre' => 'rock',
                'style' => 'alternatif',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'doolittle',
            ],
            [
                'title' => 'Loveless',
                'cover' => '1-placeholder.png',
                'year' => '1991',
                'artist' => 'my-bloody-valentine',
                'genre' => 'rock',
                'style' => 'shoegaze',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'concentre'],
                'reference' => 'loveless',
            ],
            [
                'title' => 'The Downward Spiral',
                'cover' => '1-placeholder.png',
                'year' => '1994',
                'artist' => 'nine-inch-nails',
                'genre' => 'rock',
                'style' => 'industriel',
                'owner' => 'nicolas',
                'moods' => ['motive', 'melancolique'],
                'reference' => 'the-downward-spiral',
            ],
            [
                'title' => 'Ten',
                'cover' => '1-placeholder.png',
                'year' => '1991',
                'artist' => 'pearl-jam',
                'genre' => 'grunge',
                'owner' => 'nicolas',
                'moods' => ['motive', 'melancolique'],
                'reference' => 'ten',
            ],
            [
                'title' => 'Rage Against the Machine',
                'cover' => '1-placeholder.png',
                'year' => '1992',
                'artist' => 'rage-against-the-machine',
                'genre' => 'rock',
                'style' => 'fusion',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'rage-against-the-machine',
            ],
            [
                'title' => 'Back in Black',
                'cover' => '1-placeholder.png',
                'year' => '1980',
                'artist' => 'ac-dc',
                'genre' => 'rock',
                'style' => 'hard',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'back-in-black',
            ],
            [
                'title' => 'Blood Sugar Sex Magik',
                'cover' => '1-placeholder.png',
                'year' => '1991',
                'artist' => 'red-hot-chili-peppers',
                'genre' => 'rock',
                'style' => 'funk',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'blood-sugar-sex-magik',
            ],
            [
                'title' => 'Hybrid Theory',
                'cover' => '1-placeholder.png',
                'year' => '2000',
                'artist' => 'linkin-park',
                'genre' => 'rock',
                'style' => 'nu-metal',
                'owner' => 'nicolas',
                'moods' => ['motive', 'melancolique'],
                'reference' => 'hybrid-theory',
            ],
            [
                'title' => 'Brothers',
                'cover' => '1-placeholder.png',
                'year' => '2010',
                'artist' => 'the-black-keys',
                'genre' => 'rock',
                'style' => 'blues',
                'owner' => 'nicolas',
                'moods' => ['paisible', 'concentre'],
                'reference' => 'brothers',
            ],
            [
                'title' => 'Songs in the Key of Life',
                'cover' => '1-placeholder.png',
                'year' => '1976',
                'artist' => 'stevie-wonder',
                'genre' => 'soul',
                'owner' => 'nicolas',
                'moods' => ['amoureux', 'paisible'],
                'reference' => 'songs-in-the-key-of-life',
            ],
            [
                'title' => 'Demon Days',
                'cover' => '1-placeholder.png',
                'year' => '2005',
                'artist' => 'gorillaz',
                'genre' => 'electro',
                'style' => 'trip-hop',
                'owner' => 'nicolas',
                'moods' => ['concentre', 'melancolique'],
                'reference' => 'demon-days',
            ],
            [
                'title' => 'The Suburbs',
                'cover' => '1-placeholder.png',
                'year' => '2010',
                'artist' => 'arcade-fire',
                'genre' => 'rock',
                'style' => 'indie',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'paisible'],
                'reference' => 'the-suburbs',
            ],
            [
                'title' => 'Fetch the Bolt Cutters',
                'cover' => '1-placeholder.png',
                'year' => '2020',
                'artist' => 'fiona-apple',
                'genre' => 'indie',
                'style' => 'alternatif',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'concentre'],
                'reference' => 'fetch-the-bolt-cutters',
            ],
            [
                'title' => 'Hounds of Love',
                'cover' => '1-placeholder.png',
                'year' => '1985',
                'artist' => 'kate-bush',
                'genre' => 'rock',
                'style' => 'art-pop',
                'owner' => 'nicolas',
                'moods' => ['melancolique', 'paisible'],
                'reference' => 'hounds-of-love',
            ],
            [
                'title' => 'Sound of Silver',
                'cover' => '1-placeholder.png',
                'year' => '2007',
                'artist' => 'lcd-soundsystem',
                'genre' => 'electro',
                'style' => 'dance-punk',
                'owner' => 'nicolas',
                'moods' => ['motive', 'en-soiree'],
                'reference' => 'sound-of-silver',
            ],
            [
                'title' => 'Innervisions',
                'cover' => '1-placeholder.png',
                'year' => '1973',
                'artist' => 'stevie-wonder',
                'genre' => 'soul',
                'owner' => 'nicolas',
                'moods' => ['paisible', 'amoureux'],
                'reference' => 'innervisions',
            ],
        ];

        foreach($datas as $data) {
            $album = (new Album())
                ->setTitle($data['title'])
                ->setCover($data['cover'] ?? null)
                ->setYear($data['year'] ?? null)
                ->setArtist($this->getReference('artist-' . $data['artist'], Artist::class))
                ->setGenre(isset($data['genre']) ? $this->getReference('genre-' . $data['genre'], Genre::class) : null)
                ->setStyle(isset($data['style']) ? $this->getReference('style-' . $data['style'], Style::class) : null)
                ->setOwner($this->getReference('user-' . $data['owner'], User::class));
            if(isset($data['moods'])) {
                foreach($data['moods'] as $mood) {
                    $album->addMood($this->getReference('mood-' . $mood, Mood::class));
                }
            }
            $manager->persist($album);
            $this->addReference('album-' . $data['reference'], $album);
        }

        $manager->flush();
    }

    public function getOrder(): int
    {
        return 7;
    }
}
